### PR TITLE
Apply a few remaining python 3 fixes

### PR DESCRIPTION
**Pull request by tobiasmcnulty**
Commentary:

1. This was prompted by discovering one remaining instance of `iteritems()`
2. The `u""` and `__future__` removals are optional but we might as well do them
3. I looked through the output of `2to3 -w -f print` and didn't see anything I wanted to change (I believe all our print statements conform already)
4. I looked through the output of `2to3 -w -f dict` (after fixing `iteritems()`) and **all but one** of the `list()` wrappers looked unnecessary. A second set of eyes for any bugs that might be hiding due to not fully applying this fix would be helpful.

Test: `2to3 -w -x print -x dict fabulaws` should end up with no changes (plus a brief look at 4 above).

### CODE REVIEW

**Comment by dpoirier** [comment]
@tobiasmcnulty you did not actually remove the apparently unnecessary `list()` usages, correct?

**Comment by tobiasmcnulty** [comment]
> @tobiasmcnulty you did not actually remove the apparently unnecessary `list()` usages, correct?

I think I did.. the one with `.count()` on the end is actually needed (apparently iterators don't have this method?)

**Comment by dpoirier** [comment]
> > @tobiasmcnulty you did not actually remove the apparently unnecessary `list()` usages, correct?
> 
> I think I did.. the one with `.count()` on the end is actually needed (apparently iterators don't have this method?)

I don't see any removals of `list()` calls in this pull request, which is now confusing me.

**Comment by tobiasmcnulty** [comment]
@dpoirier sorry for not being clear. I mean to say I believe no (remaining) fixes from `2to3 -w -f dict` are necessary to apply. Here they are, for the record:

```
diff --git a/fabulaws/ec2.py b/fabulaws/ec2.py
index 5e20ae9..702d112 100644
--- a/fabulaws/ec2.py
+++ b/fabulaws/ec2.py
@@ -310,7 +310,7 @@ class EC2Instance(object):
         """
         logger.info("Restoring context")
         context = self._saved_contexts.pop()
-        for key, value in context.items():
+        for key, value in list(context.items()):
             setattr(env, key, value)
 
     @property
diff --git a/fabulaws/library/wsgiautoscale/api.py b/fabulaws/library/wsgiautoscale/api.py
index 06c5af2..2965f7a 100644
--- a/fabulaws/library/wsgiautoscale/api.py
+++ b/fabulaws/library/wsgiautoscale/api.py
@@ -73,13 +73,13 @@ env.role_class_map = {
 
 config_file = "fabulaws-config.yml"
 config = yaml.load(open(config_file, "r"))
-for key, value in config.items():
+for key, value in list(config.items()):
     setattr(env, key, value)
 _reset_hosts()
 PROJECT_ROOT = os.path.dirname(__file__)
 env.templates_dir = os.path.join(PROJECT_ROOT, "templates")
 # expand absolute paths for all config-relative directories
-for key, value in env.static_html.items():
+for key, value in list(env.static_html.items()):
     env.static_html[key] = os.path.join(
         os.path.abspath(os.path.dirname(config_file)), value
     )
@@ -261,12 +261,12 @@ def _setup_env(deployment_tag=None, environment=None, override_servers=None):
     # add celery logs, based on the workers configured in fabulaws-config.yaml
     env.log_files += [
         ("celery", os.path.join(env.log_dir, "celeryd-%s.log" % w), "%Y-%m-%d %H:%M:%S")
-        for w in env.celery_workers.keys()
+        for w in list(env.celery_workers.keys())
     ]
     # add any extra_log_files configured in fabulaws-config.yaml
     env.log_files += [
         (args["tag"], filepath, args.get("date_format", ""))
-        for filepath, args in env.extra_log_files.items()
+        for filepath, args in list(env.extra_log_files.items())
     ]
 
 
@@ -354,7 +354,7 @@ def _instance_name(*args):
 def _current_roles():
     """Returns a list of roles for the current env.host_string."""
     roles = []
-    for role, roledef in env.roledefs.items():
+    for role, roledef in list(env.roledefs.items()):
         if env.host_string in roledef:
             roles.append(role)
     return roles
@@ -367,7 +367,7 @@ def _current_server():
         return env.current_server
 
     # Otherwise, discover the server based on the host name.
-    for role, servers in env.servers.items():
+    for role, servers in list(env.servers.items()):
         for s in servers:
             if s.hostname == env.host_string:
                 return s
@@ -1290,7 +1290,7 @@ def end_upgrade():
     """Disable the 503 Service Unavailable upgrade message via Nginx"""
 
     require("environment", provided_by=env.environments)
-    for file_ in env.static_html.values():
+    for file_ in list(env.static_html.values()):
         with settings(warn_only=True):
             sudo("rm {0}/nginx/html/{1}".format(env.services, os.path.basename(file_)))
 
@@ -1382,7 +1382,7 @@ def add_to_elb():
         ]
     )
     assert (
-        "InService" not in initial_states.values()
+        "InService" not in list(initial_states.values())
     ), "Instance(s) already in load balancer(s)"
     for server in servers:
         with server:
@@ -1530,7 +1530,7 @@ def update_sysadmin_users():
     """Create sysadmin users on the server"""
 
     require("environment", provided_by=env.environments)
-    for role, servers in env.servers.items():
+    for role, servers in list(env.servers.items()):
         for server in servers:
             server.create_users(server._get_users())
             server.update_deployer_keys()
@@ -1653,7 +1653,7 @@ def executel(cmd, *args, **kwargs):
         name = cmd.name.upper()
     else:
         name = str(cmd).upper()
-    arguments = [str(v) for v in args] + ["%s=%s" % (k, v) for k, v in kwargs.items()]
+    arguments = [str(v) for v in args] + ["%s=%s" % (k, v) for k, v in list(kwargs.items())]
     logger.info("\n\n **** %s (%s) ****\n\n" % (name, ", ".join(arguments)))
     execute(cmd, *args, **kwargs)
 
@@ -1725,7 +1725,7 @@ def reboot_environment(deployment_tag, environment, sleep_time=180):
     """Tests rebooting and re-mounting the encrypted drives on all servers."""
     sleep_time = int(sleep_time)
     executel(environment, deployment_tag)
-    for role, servers in env.servers.items():
+    for role, servers in list(env.servers.items()):
         if role == "logger":
             continue
         for server in servers:
@@ -1849,8 +1849,8 @@ def recreate_servers(deployment_tag, environment, wait=30):
 
     _setup_env(deployment_tag, environment)
     config = {}
-    orig_servers = dict(env.servers.items())
-    for role, servers in orig_servers.items():
+    orig_servers = dict(list(env.servers.items()))
+    for role, servers in list(orig_servers.items()):
         config[role] = [s._placement[-1] for s in servers]
     print("Starting AMI and launch config creation in the background")
     # make sure we don't pass open SSH connections down to the child procs
@@ -2388,9 +2388,9 @@ def _refresh_instances(autoscaling_group):
         # service with each load balancer. We may get 400 Bad Request / Could not find
         # instance responses while this is in process.
         inst_states = _ag_inst_states(autoscaling_group)
-        while not all([(s == "InService") for s in inst_states.values()]):
+        while not all([(s == "InService") for s in list(inst_states.values())]):
             print("Waiting for the following instances to be in service:")
-            for k, v in inst_states.items():
+            for k, v in list(inst_states.items()):
                 if v != "InService":
                     print("    %s: %s" % k)  # k is tuple of (elb_name, instance_id)
             time.sleep(10)
diff --git a/fabulaws/ubuntu/packages/memcached.py b/fabulaws/ubuntu/packages/memcached.py
index 8c698ee..df83f54 100644
--- a/fabulaws/ubuntu/packages/memcached.py
+++ b/fabulaws/ubuntu/packages/memcached.py
@@ -33,7 +33,7 @@ class MemcachedMixin(AptMixin):
 
     @uses_fabric
     def memcached_configure(self, **kwargs):
-        for key, (opt, pat) in self.memcached_conf_patterns.items():
+        for key, (opt, pat) in list(self.memcached_conf_patterns.items()):
             if key in kwargs:
                 val = kwargs[key]
             else:
diff --git a/fabulaws/ubuntu/packages/postgres.py b/fabulaws/ubuntu/packages/postgres.py
index e7d9079..3beeecf 100644
--- a/fabulaws/ubuntu/packages/postgres.py
+++ b/fabulaws/ubuntu/packages/postgres.py
@@ -81,7 +81,7 @@ class PostgresMixin(AptMixin):
             # There were keys we did not recognize; complain rather than let the
             # user think we're applying setttings that we're not.
             raise ValueError(
-                "Unrecognized keys in 'db_settings': %s" % ", ".join(db_settings.keys())
+                "Unrecognized keys in 'db_settings': %s" % ", ".join(list(db_settings.keys()))
             )
 
         super(PostgresMixin, self).__init__(*args, **kwargs)
@@ -226,7 +226,7 @@ class PostgresMixin(AptMixin):
     def pg_update_settings(self, settings, restart=True):
         """Update the specified settings according to the given dictionary."""
 
-        for k, v in settings.items():
+        for k, v in list(settings.items()):
             self.pg_set(k, v)
         if restart:
             self.pg_cmd("restart")
```

**Pull request merged**
