### PR TITLE
Use security group ids

### PR DESCRIPTION
**Pull request by dpoirier**
Apparent behavior change with VPC's.  Seem to need to
use security group IDs instead of names when creating
launch configuration.

### CODE REVIEW

**Comment by vkurup** [comment]
Looks reasonable to me :+1:

**Comment by dpoirier** [comment]
What worries me about this is whether it'll break fabulaws on EC2 classic (non-VPC) deploys.

**Comment by dpoirier** [comment]
I've updated this in a way that should make it backward compatible.

**Comment by tobiasmcnulty** [comment]
:+1:

In addition to the reasons you mention I like this change b/c the method now always returns something if `security_groups` is set.

**Pull request merged**
